commit

diff --git a/os/unix/history/unixprogenv/exercises/chapter_5/5-30/get b/os/unix/history/unixprogenv/exercises/chapter_5/5-30/get
--- a/os/unix/history/unixprogenv/exercises/chapter_5/5-30/get
+++ b/os/unix/history/unixprogenv/exercises/chapter_5/5-30/get
@@ -6,7 +6,7 @@ PATH=/bin:/usr/bin
 GPHISTDIR=$HOME/.gphist
 
 if test ! -d $GPHISTDIR; then
-	echo "History directory $GPHISTDIR not found" >1&2; exit 1
+	echo "History directory $GPHISTDIR not found" 1>&2; exit 1
 fi
 
 VERSION=0
